name: API Test Automation

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML-Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run "Practice Software Testing API.postman_collection.json" --reporters cli,htmlextra --reporter-htmlextra-export "reports/htmlout.html"

      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: reports/htmlout.html